/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rexgo_net_liquid_RexgoVid */

#ifndef _Included_rexgo_net_liquid_RexgoVid
#define _Included_rexgo_net_liquid_RexgoVid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rexgo_net_liquid_RexgoVid
 * Method:    native_start
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_rexgo_net_liquid_RexgoVid_native_1start
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     rexgo_net_liquid_RexgoVid
 * Method:    native_stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rexgo_net_liquid_RexgoVid_native_1stop
  (JNIEnv *, jobject);

/*
 * Class:     rexgo_net_liquid_RexgoVid
 * Method:    native_update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rexgo_net_liquid_RexgoVid_native_1update
  (JNIEnv *, jobject);

/*
 * Class:     rexgo_net_liquid_RexgoVid
 * Method:    native_imageCopy
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_rexgo_net_liquid_RexgoVid_native_1imageCopy
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
